// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArWJKqEvcI-n8saYcAFYf7IG1Y2y_L7O4',
    appId: '1:157703567144:web:ef0f1be103a98fa99a021d',
    messagingSenderId: '157703567144',
    projectId: 'ecomer-2d103',
    authDomain: 'ecomer-2d103.firebaseapp.com',
    storageBucket: 'ecomer-2d103.appspot.com',
    measurementId: 'G-MVGERDDKRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCidsscGTNY1f5ZKndUVElAFEm1O8KSbUc',
    appId: '1:157703567144:android:a5ca06a805f320069a021d',
    messagingSenderId: '157703567144',
    projectId: 'ecomer-2d103',
    storageBucket: 'ecomer-2d103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANqrw_bPcL5b2SeET7SgJvJr9rdgLaXDw',
    appId: '1:157703567144:ios:4360c316e71a77a49a021d',
    messagingSenderId: '157703567144',
    projectId: 'ecomer-2d103',
    storageBucket: 'ecomer-2d103.appspot.com',
    iosBundleId: 'com.example.ecomerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANqrw_bPcL5b2SeET7SgJvJr9rdgLaXDw',
    appId: '1:157703567144:ios:cd2e7c299001c79e9a021d',
    messagingSenderId: '157703567144',
    projectId: 'ecomer-2d103',
    storageBucket: 'ecomer-2d103.appspot.com',
    iosBundleId: 'com.example.ecomerce.RunnerTests',
  );
}
